const imageArray = [
  "Pokieatsimages/abra.avif",
  "Pokieatsimages/aerodactyl.avif",
  "Pokieatsimages/alakazam.avif",
  "Pokieatsimages/arbok.avif",
  "Pokieatsimages/arcanine.avif",
  "Pokieatsimages/articuno.avif",
  "Pokieatsimages/beedrill.avif",
  "Pokieatsimages/bellsprout.avif",
  "Pokieatsimages/blastoise.avif",
  "Pokieatsimages/bulbasaur.avif",
  "Pokieatsimages/butterfree.avif",
  "Pokieatsimages/caterpie.avif",
  "Pokieatsimages/chansey.avif",
  "Pokieatsimages/charizard.avif",
  "Pokieatsimages/charizard.avif",
  "Pokieatsimages/charmander.avif",
  "Pokieatsimages/charmeleon.avif",
  "Pokieatsimages/clefable.avif",
  "Pokieatsimages/clefairy.avif",
  "Pokieatsimages/cloyster.avif",
  "Pokieatsimages/cubone.avif",
  "Pokieatsimages/dewgong.avif",
  "Pokieatsimages/diglett.avif",
  "Pokieatsimages/ditto.avif",
  "Pokieatsimages/dodrio.avif",
  "Pokieatsimages/doduo.avif",
  "Pokieatsimages/dragonair.avif",
  "Pokieatsimages/dragonite.avif",
  "Pokieatsimages/dratini.avif",
  "Pokieatsimages/drowzee.avif",
  "Pokieatsimages/dugtrio.avif",
  "Pokieatsimages/eevee.avif",
  "Pokieatsimages/ekans.avif",
  "Pokieatsimages/electabuzz.avif",
  "Pokieatsimages/electrode.avif",
  "Pokieatsimages/exeggcute.avif",
  "Pokieatsimages/exeggutor.avif",
  "Pokieatsimages/farfetchd.avif",
  "Pokieatsimages/fearow.avif",
  "Pokieatsimages/flareon.avif",
  "Pokieatsimages/gastly.avif",
  "Pokieatsimages/gengar.avif",
  "Pokieatsimages/geodude.avif",
  "Pokieatsimages/gloom.avif",
  "Pokieatsimages/golbat.avif",
  "Pokieatsimages/goldeen.avif",
  "Pokieatsimages/golduck.avif",
  "Pokieatsimages/golem.avif",
  "Pokieatsimages/graveler.avif",
  "Pokieatsimages/grimer.avif",
  "Pokieatsimages/growlithe.avif",
  "Pokieatsimages/haunter.avif",
  "Pokieatsimages/hitmonchan.avif",
  "Pokieatsimages/hitmonlee.avif",
  "Pokieatsimages/horsea.avif",
  "Pokieatsimages/hypno.avif",
  "Pokieatsimages/ivysaur.avif",
  "Pokieatsimages/jigglypuff.avif",
  "Pokieatsimages/jolteon.avif",
  "Pokieatsimages/jynx.avif",
  "Pokieatsimages/kabuto.avif",
  "Pokieatsimages/kabutops.avif",
  "Pokieatsimages/kadabra.avif",
  "Pokieatsimages/kakuna.avif",
  "Pokieatsimages/kangaskhan.avif",
  "Pokieatsimages/kingler.avif",
  "Pokieatsimages/koffing.avif",
  "Pokieatsimages/krabby.avif",
  "Pokieatsimages/lapras.avif",
  "Pokieatsimages/lickitung.avif",
  "Pokieatsimages/machamp.avif",
  "Pokieatsimages/machoke.avif",
  "Pokieatsimages/machop.avif",
  "Pokieatsimages/magikarp.avif",
  "Pokieatsimages/magikarp.avif",
  "Pokieatsimages/magmar.avif",
  "Pokieatsimages/magneton.avif",
  "Pokieatsimages/mankey.avif",
  "Pokieatsimages/marowak.avif",
  "Pokieatsimages/meowth.avif",
  "Pokieatsimages/metapod.avif",
  "Pokieatsimages/mew.avif",
  "Pokieatsimages/mewtwo.avif",
  "Pokieatsimages/moltres.avif",
  "Pokieatsimages/mr-mime.avif",
  "Pokieatsimages/muk.avif",
  "Pokieatsimages/nidoking.avif",
  "Pokieatsimages/nidoqueen.avif",
  "Pokieatsimages/nidoran-f.avif",
  "Pokieatsimages/nidoran-m.avif",
  "Pokieatsimages/nidorina.avif",
  "Pokieatsimages/nidorino.avif",
  "Pokieatsimages/ninetales.avif",
  "Pokieatsimages/oddish.avif",
  "Pokieatsimages/omanyte.avif",
  "Pokieatsimages/omastar.avif",
  "Pokieatsimages/onix.avif",
  "Pokieatsimages/paras.avif",
  "Pokieatsimages/parasect.avif",
  "Pokieatsimages/persian.avif",
  "Pokieatsimages/pidgeot.avif",
  "Pokieatsimages/pidgeotto.avif",
  "Pokieatsimages/pidgey.avif",
  "Pokieatsimages/pikachu.avif",
  "Pokieatsimages/pinsir.avif",
  "Pokieatsimages/poliwag.avif",
  "Pokieatsimages/poliwhirl.avif",
  "Pokieatsimages/poliwrath.avif",
  "Pokieatsimages/ponyta.avif",
  "Pokieatsimages/porygon.avif",
  "Pokieatsimages/primeape.avif",
  "Pokieatsimages/psyduck.avif",
  "Pokieatsimages/raichu.avif",
  "Pokieatsimages/rapidash.avif",
  "Pokieatsimages/raticate.avif",
  "Pokieatsimages/rattata.avif",
  "Pokieatsimages/rhyhorn.avif",
  "Pokieatsimages/sandshrew.avif",
  "Pokieatsimages/sandslash.avif",
  "Pokieatsimages/scyther.avif",
  "Pokieatsimages/seadra.avif",
  "Pokieatsimages/seaking.avif",
  "Pokieatsimages/seel.avif",
  "Pokieatsimages/shellder.avif",
  "Pokieatsimages/slowbro.avif",
  "Pokieatsimages/slowpoke.avif",
  "Pokieatsimages/snorlax.avif",
  "Pokieatsimages/spearow.avif",
  "Pokieatsimages/squirtle.avif",
  "Pokieatsimages/starmie.avif",
  "Pokieatsimages/staryu.avif",
  "Pokieatsimages/tangela.avif",
  "Pokieatsimages/tauros.avif",
  "Pokieatsimages/tentacool.avif",
  "Pokieatsimages/tentacruel.avif",
  "Pokieatsimages/vaporeon.avif",
  "Pokieatsimages/venomoth.avif",
  "Pokieatsimages/venonat.avif",
  "Pokieatsimages/venusaur.avif",
  "Pokieatsimages/victreebel.avif",
  "Pokieatsimages/vileplume.avif",
  "Pokieatsimages/voltorb.avif",
  "Pokieatsimages/vulpix.avif",
  "Pokieatsimages/wartortle.avif",
  "Pokieatsimages/weedle.avif",
  "Pokieatsimages/weedle.avif",
  "Pokieatsimages/weepinbell.avif",
  "Pokieatsimages/weezing.avif",
  "Pokieatsimages/wigglytuff.avif",
  "Pokieatsimages/zapdos.avif",
  "Pokieatsimages/zubat.avif",
];

const promptArray = [
  "You are on an island. There is nothing else.",
  "If you don't eat it the world ends.",
  "You are completely fine. It's just for luxery.",
  "You have to vote for the other guy if you don't.",
  "It's either this or a pile of thumtacks.",
  "It's either this or going blind.",
  "Your mother prepared it for you.",
  "Your grandmother prepared it for you.",
  "It has a wife and kids, but so do you and there is nothing else.",
  "If you don't eat this you will have to resort to your dog.",
  "It's either this or your best friend.",
  "For 1 Million Dollars?",
  "For 1 Billion Dollars?",
  "For Narnia?",
  "For Rome?",
  "For Sparta?",
  "For 5 dollars?",
  "Would you do it for 10 dollars?",
];
function getRandomImage() {
  if (imageArray.length === 0) {
    alert("No more images to display.");
    return;
  }

  const num = Math.floor(Math.random() * imageArray.length);
  const img = imageArray[num];
  const promptNum = Math.floor(Math.random() * promptArray.length);
  const prompt = promptArray[promptNum];

  document.getElementById("choiceimage").src = img;
  document.getElementById("prompt").textContent = prompt;

  imageArray.splice(num, 1); // Remove the selected image from the array
}
